dbt_training:
  outputs:
    dev:
      account: yl45797.east-us-2.azure
      database: analytics_009
      password: QAG7YfCMUmtm2t0A
      role: developer_009
      schema: dbt_hoang
      threads: 1
      type: snowflake
      user: student009
      warehouse: developer_wh_009
    prod:
      account: yl45797.east-us-2.azure
      database: analytics_009
      password: QAG7YfCMUmtm2t0A
      role: developer_009
      schema: hoanghce
      threads: 1
      type: snowflake
      user: student009
      warehouse: developer_wh_009
  target: dev
